# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mask_detect.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mask_detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mask_detect.proto\x12\x0bmask_detect\"\x1f\n\x0b\x43lientInput\x12\x10\n\x08\x62\x36\x34_data\x18\x01 \x01(\t\"6\n\x0bMaskDetData\x12\r\n\x05label\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\"=\n\x0cServerOutput\x12-\n\x0bmask_detect\x18\x01 \x01(\x0b\x32\x18.mask_detect.MaskDetData2R\n\nMaskDetect\x12\x44\n\x0b\x44\x65tectMasks\x12\x18.mask_detect.ClientInput\x1a\x19.mask_detect.ServerOutput\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mask_detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINPUT']._serialized_start=34
  _globals['_CLIENTINPUT']._serialized_end=65
  _globals['_MASKDETDATA']._serialized_start=67
  _globals['_MASKDETDATA']._serialized_end=121
  _globals['_SERVEROUTPUT']._serialized_start=123
  _globals['_SERVEROUTPUT']._serialized_end=184
  _globals['_MASKDETECT']._serialized_start=186
  _globals['_MASKDETECT']._serialized_end=268
# @@protoc_insertion_point(module_scope)
