apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks/kafka-data
  storageClassName: local-path
