apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks/zookeeper-data
  storageClassName: local-path
