# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_liveness_detect.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'face_liveness_detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66\x61\x63\x65_liveness_detect.proto\x12\x14\x66\x61\x63\x65_liveness_detect\"\x1f\n\x0b\x43lientInput\x12\x10\n\x08\x62\x36\x34_data\x18\x01 \x01(\t\">\n\x10\x46\x61\x63\x65LivenessData\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\"M\n\x0cServerOutput\x12=\n\rface_liveness\x18\x01 \x01(\x0b\x32&.face_liveness_detect.FaceLivenessData2o\n\x12\x46\x61\x63\x65LivenessDetect\x12Y\n\x0e\x44\x65tectLiveness\x12!.face_liveness_detect.ClientInput\x1a\".face_liveness_detect.ServerOutput\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_liveness_detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINPUT']._serialized_start=52
  _globals['_CLIENTINPUT']._serialized_end=83
  _globals['_FACELIVENESSDATA']._serialized_start=85
  _globals['_FACELIVENESSDATA']._serialized_end=147
  _globals['_SERVEROUTPUT']._serialized_start=149
  _globals['_SERVEROUTPUT']._serialized_end=226
  _globals['_FACELIVENESSDETECT']._serialized_start=228
  _globals['_FACELIVENESSDETECT']._serialized_end=339
# @@protoc_insertion_point(module_scope)
