# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import face_liveness_detect_pb2 as face__liveness__detect__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in face_liveness_detect_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceLivenessDetectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectLiveness = channel.unary_unary(
                '/face_liveness_detect.FaceLivenessDetect/DetectLiveness',
                request_serializer=face__liveness__detect__pb2.ClientInput.SerializeToString,
                response_deserializer=face__liveness__detect__pb2.ServerOutput.FromString,
                _registered_method=True)


class FaceLivenessDetectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectLiveness(self, request, context):
        """A simple RPC.

        Obtains the MessageResponse at a given position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceLivenessDetectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectLiveness': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLiveness,
                    request_deserializer=face__liveness__detect__pb2.ClientInput.FromString,
                    response_serializer=face__liveness__detect__pb2.ServerOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_liveness_detect.FaceLivenessDetect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('face_liveness_detect.FaceLivenessDetect', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceLivenessDetect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectLiveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_liveness_detect.FaceLivenessDetect/DetectLiveness',
            face__liveness__detect__pb2.ClientInput.SerializeToString,
            face__liveness__detect__pb2.ServerOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
